### ISSUE TITLE
CherryMusic 1.0 Roadmap

### ISSUE THREAD

**Issue by devsnd** [devsnd/cherrymusic#628]
This is my fifth attempt at (re)writing CherryMusic and it looks quite good and maintainable right now. The codebase for this new version is a new client, the backend stays mostly the same for now. but I'm still experimenting a bit so I cannot accept any help or pull requests for this new version. So I'll just make a list of stuff that needs to happen before it can be released, so you guys know whats going on and whats taking so long.

Features for feature-parity:
 - [ ] login screen
 - [ ] basic file browsing
 - [ ] basic search
 - [ ] independently scrollable browser and playlists
 - [ ] meta data fetching
 - [ ] basic playlist functionality (tabs, adding / listing tracks, playing next track after current finished)
 - [ ] basic audio player (play, pause, seek)
 - [ ] compact file listing
 - [ ] switch between list and tile view in browser
 - [ ] drag'n'drop support to order tracks in playlist
 - [ ] playlist browser - show playlist list
 - [ ] playlist browser - delete playlist
 - [ ] playlist browser - mark playlist as public
 - [ ] playlist browser - load single playlist
 - [ ] save changed playlist
 - [ ] save new playlist
 - [ ] prohibit closing the browser tab while playing
 - [ ] transcoding (based on browser and server capabilities)
 - [ ] load server config on startup
 - [ ] load user options on startup
 - [ ] options - change user options
 - [ ] options - keyboard shortcuts
 - [ ] options - change password dialog
 - [ ] options - export playlists to zip
 - [ ] admin - create user
 - [ ] admin - active user list (allow download & delete user)
 - [ ] admin - trigger db update
 - [ ] bind keyboard shortcuts to actions
 - [ ] about dialog
 - [ ] playlist sorting
 - [ ] generate random playlist
 - [ ] download playlist
 - [ ] remaining tracks / playtime display
 - [ ] change album art dialog

Issues fixed by the rewrite:
 - [ ] playlist manager tries to access non-existing playlist #578 
 - [ ] Don't fetch the same meta-data twice #460 
 - [ ] Lazy loading meta-info for tracks #439 
 - [ ] Seekbar does not work. #275 
 - [ ] jPlayer :: seek outside of the buffered zone #571

**Comment by yebo29** [comment]
Can't wait to see the new version. Keep up the good work :)

**Comment by jsulinski** [comment]
Have you considered adding video? I love cherrymusic, but sometimes I miss seeing videos too. 

I wrote some ugly bash around youtube-dl to rip opus and move into /music for cherrymusic and replaced youtube/spotify. Thanks so much for your work on this project.
